const LOCALIZATION_KEYS = {
  MODAL_FULLSCREEN_DESCRIPTION: "modal_fullscreen_description",
  MODAL_BUTTON_ARIA_DESCRIPTION: "modal_button_aria_description",
  MODAL_CLOSE: "modal_close",
  OPEN_CATEGORY_MENU: "open_category_menu",
  OPEN_CATEGORY_TEXT: "open_category_text",
  ORCA_LOGO_ALT: "orca_logo_alt",
  WEBSITE_URL_ORCA: "website_url_orca",
  ORCA_LINK_TITLE: "orca_link_title",
  CATEGORIES: "categories",
  CONTACT: "contact",
  EMAIL_ADDRESS_ORCA: "email_address_orca",
  SEND_SUPPORT_REQUEST: "send_support_request",
  INPUT_SEARCH_ID: "input_search_id",
  INPUT_SEARCH_PLACEHOLDER: "input_search_placeholder",
  SEARCHING_IN_ALL_CATEGORIES: "searching_in_all_categories",
  SEARCHING_IN_CATEGORY: "searching_in_category",
  SEARCH_NO_CONTENT_FOUND: "search_no_content_found",
  NO_SEARCH_NO_CONTENT_FOUND: "no_search_no_content_found",
  EXPAND_DESCRIPTION: "expand_description",
  COLLAPSE_DESCRIPTION: "collapse_description",
  BUTTON_SELECT: "button_select",
  PAGINATION_LABEL: "pagination_label",
  PAGINATION_NEXT: "pagination_next",
  PAGINATION_PREV: "pagination_prev", 
  ERROR:"error",
  CATEGORY_MENU_CLOSE: "category_menu_close",
  SELECT_COURSE_ARIA_1: "select_course_aria_1",
  SELECT_COURSE_ARIA_2: "select_course_aria_2",
  INPUT_SEARCH_ARIA: "input_search_aria",
};

export default LOCALIZATION_KEYS;
